
CREATE TABLE roles(
 id SERIAL PRIMARY KEY,
 name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE users(
 id SERIAL PRIMARY KEY,
 name VARCHAR(100),
 email VARCHAR(255) UNIQUE NOT NULL,
 password_hash TEXT NOT NULL,
 role_id INT REFERENCES roles(id),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
